### ISSUE TITLE
Crashes when creating a profile without a wifi connection

### ISSUE THREAD

**Issue by nnam-ibe** [nnam-ibe/Pro-Fi#11]
Steps to reproduce
* Turn off wifi
* Try to add a new profile

**Comment by OGBA-B** [comment]
so I found out that the method getConfiguredNetworks() returns null if the WIFI is turned off.
I was unable to find a way to get the list without turning on the WIFI so we might need to add a dialogue asking the user to turn on WIFI before going to the next activity.

**Comment by nnam-ibe** [comment]
Yea that makes sense.
