### ISSUE TITLE
(1.0 Patch) Profile is hidden behind add button when 5 have added added

### ISSUE THREAD

**Issue by OGBA-B** [nnam-ibe/Pro-Fi#24]
The 5th profile card gets hidden behind the add button and the scroll function does not bring up the profile.
The goal is to modify the scroll layout so that new profiles will always be above the add button.

**Comment by nnam-ibe** [comment]
So the floating button is covering parts of the profile card right?

That's how is supposed to be, cause you shouldn't have layouts higher that
your floating button.

I think we should either add a buffer to the end, so you can scroll to the
point that nothing is covered, or have is so the floating button disappears
when you start scrolling.

**Comment by OGBA-B** [comment]
Makes sense, I'll add the buffer. Thank you.
